# Generated by Django 4.0.4 on 2022-06-17 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=32, verbose_name='项目名称')),
            ],
        ),
        migrations.CreateModel(
            name='MockInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=50, verbose_name='接口名称')),
                ('interface_url', models.CharField(max_length=64, verbose_name='接口地址')),
                ('is_open', models.SmallIntegerField(choices=[(1, '开'), (0, '关')], verbose_name='是否打开')),
                ('response', models.CharField(max_length=500, verbose_name='返回信息')),
                ('method', models.CharField(max_length=10, verbose_name='请求方式')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MockInterPlatform.project', verbose_name='项目名称')),
            ],
        ),
    ]
