# Generated by Django 4.0.4 on 2022-06-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MockInterPlatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterface',
            name='request_parms',
            field=models.CharField(default='', max_length=200, verbose_name='请求参数'),
        ),
    ]
