# Generated by Django 4.0.3 on 2022-05-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='docs',
            field=models.CharField(default='描述', max_length=100, verbose_name='描述'),
        ),
    ]
