# Generated by Django 4.0.3 on 2022-05-11 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test_App', '0002_department_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='creat_time',
            field=models.DateField(verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test_App.department', verbose_name='部门'),
        ),
    ]
