# Generated by Django 4.0.3 on 2022-05-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_App', '0003_alter_userinfo_creat_time_alter_userinfo_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='creat_time',
            field=models.DateTimeField(verbose_name='入职时间'),
        ),
    ]
