# Generated by Django 4.0.3 on 2022-05-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_App', '0004_alter_userinfo_creat_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='creat_time',
            field=models.DateField(verbose_name='入职时间'),
        ),
    ]
