# Generated by Django 4.0.3 on 2022-05-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_App', '0005_alter_userinfo_creat_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='靓号')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('level', models.SmallIntegerField(choices=[(1, 'SVIP'), (2, 'VIP'), (3, 'NORMAL')], default=3, verbose_name='级别')),
                ('status', models.SmallIntegerField(choices=[(1, '已占用'), (0, '未占用')], default=0, verbose_name='状态')),
            ],
        ),
    ]
